# -*- coding: utf-8 -*-
"""Gapminder with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utk4VsinqZ4kBSLTQrMvdjXRbbokm4U4
"""

# plotly_express for creating interactive plots
#!pip install plotly_express

import plotly_express as px


px.scatter(px.data.gapminder(), x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="continent",
           size="pop", color="country", hover_name="country", size_max=45)